load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "platform",
    hdrs = [
        "platform.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "simd",
    hdrs = [
        "simd.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":platform",
    ],
)
